// Code generated by protoc-gen-go.
// source: line.proto
// DO NOT EDIT!

/*
Package line is a generated protocol buffer package.

It is generated from these files:
	line.proto

It has these top-level messages:
	NotifyChannelRequest
	NotifyChannelResponse
	AppendUserRequest
	AppendUserResponse
	DeleteUserRequest
	DeleteUserResponse
*/
package line

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotifyChannelRequest struct {
	Title string                     `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Item  *NotifyChannelRequest_Item `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
}

func (m *NotifyChannelRequest) Reset()                    { *m = NotifyChannelRequest{} }
func (m *NotifyChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyChannelRequest) ProtoMessage()               {}
func (*NotifyChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NotifyChannelRequest) GetItem() *NotifyChannelRequest_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type NotifyChannelRequest_Item struct {
	Title  string                             `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Url    string                             `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Images []*NotifyChannelRequest_Item_Image `protobuf:"bytes,3,rep,name=images" json:"images,omitempty"`
	Videos []*NotifyChannelRequest_Item_Video `protobuf:"bytes,4,rep,name=videos" json:"videos,omitempty"`
}

func (m *NotifyChannelRequest_Item) Reset()                    { *m = NotifyChannelRequest_Item{} }
func (m *NotifyChannelRequest_Item) String() string            { return proto.CompactTextString(m) }
func (*NotifyChannelRequest_Item) ProtoMessage()               {}
func (*NotifyChannelRequest_Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *NotifyChannelRequest_Item) GetImages() []*NotifyChannelRequest_Item_Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *NotifyChannelRequest_Item) GetVideos() []*NotifyChannelRequest_Item_Video {
	if m != nil {
		return m.Videos
	}
	return nil
}

type NotifyChannelRequest_Item_Image struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *NotifyChannelRequest_Item_Image) Reset()         { *m = NotifyChannelRequest_Item_Image{} }
func (m *NotifyChannelRequest_Item_Image) String() string { return proto.CompactTextString(m) }
func (*NotifyChannelRequest_Item_Image) ProtoMessage()    {}
func (*NotifyChannelRequest_Item_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

type NotifyChannelRequest_Item_Video struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *NotifyChannelRequest_Item_Video) Reset()         { *m = NotifyChannelRequest_Item_Video{} }
func (m *NotifyChannelRequest_Item_Video) String() string { return proto.CompactTextString(m) }
func (*NotifyChannelRequest_Item_Video) ProtoMessage()    {}
func (*NotifyChannelRequest_Item_Video) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 1}
}

type NotifyChannelResponse struct {
}

func (m *NotifyChannelResponse) Reset()                    { *m = NotifyChannelResponse{} }
func (m *NotifyChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyChannelResponse) ProtoMessage()               {}
func (*NotifyChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AppendUserRequest struct {
	Mid string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
}

func (m *AppendUserRequest) Reset()                    { *m = AppendUserRequest{} }
func (m *AppendUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendUserRequest) ProtoMessage()               {}
func (*AppendUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AppendUserResponse struct {
}

func (m *AppendUserResponse) Reset()                    { *m = AppendUserResponse{} }
func (m *AppendUserResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendUserResponse) ProtoMessage()               {}
func (*AppendUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteUserRequest struct {
	Mid string `protobuf:"bytes,1,opt,name=mid" json:"mid,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteUserResponse struct {
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*NotifyChannelRequest)(nil), "line.NotifyChannelRequest")
	proto.RegisterType((*NotifyChannelRequest_Item)(nil), "line.NotifyChannelRequest.Item")
	proto.RegisterType((*NotifyChannelRequest_Item_Image)(nil), "line.NotifyChannelRequest.Item.Image")
	proto.RegisterType((*NotifyChannelRequest_Item_Video)(nil), "line.NotifyChannelRequest.Item.Video")
	proto.RegisterType((*NotifyChannelResponse)(nil), "line.NotifyChannelResponse")
	proto.RegisterType((*AppendUserRequest)(nil), "line.AppendUserRequest")
	proto.RegisterType((*AppendUserResponse)(nil), "line.AppendUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "line.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "line.DeleteUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Line service

type LineClient interface {
	NotifyChannel(ctx context.Context, in *NotifyChannelRequest, opts ...grpc.CallOption) (*NotifyChannelResponse, error)
	AppendUser(ctx context.Context, in *AppendUserRequest, opts ...grpc.CallOption) (*AppendUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type lineClient struct {
	cc *grpc.ClientConn
}

func NewLineClient(cc *grpc.ClientConn) LineClient {
	return &lineClient{cc}
}

func (c *lineClient) NotifyChannel(ctx context.Context, in *NotifyChannelRequest, opts ...grpc.CallOption) (*NotifyChannelResponse, error) {
	out := new(NotifyChannelResponse)
	err := grpc.Invoke(ctx, "/line.Line/NotifyChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lineClient) AppendUser(ctx context.Context, in *AppendUserRequest, opts ...grpc.CallOption) (*AppendUserResponse, error) {
	out := new(AppendUserResponse)
	err := grpc.Invoke(ctx, "/line.Line/AppendUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lineClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := grpc.Invoke(ctx, "/line.Line/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Line service

type LineServer interface {
	NotifyChannel(context.Context, *NotifyChannelRequest) (*NotifyChannelResponse, error)
	AppendUser(context.Context, *AppendUserRequest) (*AppendUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

func RegisterLineServer(s *grpc.Server, srv LineServer) {
	s.RegisterService(&_Line_serviceDesc, srv)
}

func _Line_NotifyChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineServer).NotifyChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/line.Line/NotifyChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineServer).NotifyChannel(ctx, req.(*NotifyChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Line_AppendUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineServer).AppendUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/line.Line/AppendUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineServer).AppendUser(ctx, req.(*AppendUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Line_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/line.Line/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Line_serviceDesc = grpc.ServiceDesc{
	ServiceName: "line.Line",
	HandlerType: (*LineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyChannel",
			Handler:    _Line_NotifyChannel_Handler,
		},
		{
			MethodName: "AppendUser",
			Handler:    _Line_AppendUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Line_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("line.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x36, 0x2d, 0x74, 0x44, 0xd0, 0x25, 0xd2, 0x18, 0x0f, 0x96, 0x40, 0xc1, 0x53,
	0x0e, 0xed, 0xd9, 0x43, 0xd1, 0x4b, 0x45, 0x3c, 0x2c, 0xe8, 0xbd, 0x92, 0x51, 0x17, 0x92, 0x6c,
	0xcc, 0x6e, 0x05, 0x5f, 0xd0, 0x67, 0xf0, 0xec, 0x93, 0xb8, 0xbb, 0xc9, 0x9a, 0xe8, 0xb6, 0xd4,
	0xdb, 0x6c, 0xe6, 0xff, 0xfe, 0xf9, 0x67, 0x08, 0x40, 0xc6, 0x0a, 0x4c, 0xca, 0x8a, 0x4b, 0x4e,
	0x7c, 0x5d, 0xc7, 0x1f, 0x7d, 0x08, 0xee, 0xb8, 0x64, 0x4f, 0xef, 0x57, 0x2f, 0xeb, 0xa2, 0xc0,
	0x8c, 0xe2, 0xeb, 0x06, 0x85, 0x24, 0x01, 0x0c, 0x25, 0x93, 0x19, 0x86, 0xde, 0xd4, 0xbb, 0x18,
	0xd3, 0xfa, 0x41, 0x16, 0xe0, 0x33, 0x89, 0x79, 0xd8, 0x57, 0x1f, 0x0f, 0xe6, 0xe7, 0x89, 0xf1,
	0xdb, 0xc6, 0x27, 0x2b, 0x25, 0xa3, 0x46, 0x1c, 0x7d, 0x79, 0xe0, 0xeb, 0xe7, 0x0e, 0xcf, 0x23,
	0x18, 0x6c, 0xaa, 0xcc, 0x58, 0x8e, 0xa9, 0x2e, 0xc9, 0x25, 0x8c, 0x58, 0xbe, 0x7e, 0x46, 0x11,
	0x0e, 0xa6, 0x03, 0x35, 0x67, 0xb6, 0x67, 0x4e, 0xb2, 0xd2, 0x6a, 0xda, 0x40, 0x1a, 0x7f, 0x63,
	0x29, 0x72, 0x11, 0xfa, 0xff, 0xc3, 0x1f, 0xb4, 0x9a, 0x36, 0x50, 0x74, 0x0a, 0x43, 0xe3, 0x67,
	0x83, 0x79, 0x3f, 0xc1, 0x74, 0xcb, 0x68, 0xdd, 0x56, 0x3c, 0x81, 0x93, 0x3f, 0x03, 0x44, 0xc9,
	0x0b, 0x81, 0xf1, 0x0c, 0x8e, 0x97, 0x65, 0x89, 0x45, 0x7a, 0x2f, 0xb0, 0xb2, 0xd7, 0x55, 0x7c,
	0xce, 0x52, 0xcb, 0xab, 0x32, 0x0e, 0x80, 0x74, 0x65, 0x2d, 0x7c, 0x8d, 0x19, 0x4a, 0xdc, 0x0b,
	0x77, 0x65, 0x35, 0x3c, 0xff, 0x54, 0x77, 0xbf, 0x55, 0x9b, 0x93, 0x1b, 0x38, 0xfc, 0x95, 0x8d,
	0x44, 0xbb, 0x2f, 0x12, 0x9d, 0x6d, 0xed, 0x35, 0x79, 0x7a, 0x64, 0x09, 0xd0, 0xe6, 0x24, 0x93,
	0x5a, 0xec, 0x2c, 0x18, 0x85, 0x6e, 0xa3, 0x6b, 0xd1, 0xa6, 0xb5, 0x16, 0xce, 0x9a, 0xd6, 0xc2,
	0x5d, 0x2c, 0xee, 0x3d, 0x8e, 0xcc, 0x3f, 0xbc, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xae, 0x6d,
	0x45, 0xf7, 0xd1, 0x02, 0x00, 0x00,
}
