// Code generated by protoc-gen-go.
// source: linebot/protos/linebot.proto
// DO NOT EDIT!

/*
Package linebot is a generated protocol buffer package.

It is generated from these files:
	linebot/protos/linebot.proto

It has these top-level messages:
	NotifyChannelRequest
	NotifyChannelResponse
	NotifyAppendUserRequest
	NotifyAppendUserResponse
	NotifyDeleteUserRequest
	NotifyDeleteUserResponse
	NotifyUstreamRequest
	NotifyUstreamResponse
*/
package linebot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotifyChannelRequest struct {
	To    []string                   `protobuf:"bytes,1,rep,name=to" json:"to,omitempty"`
	Title string                     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Item  *NotifyChannelRequest_Item `protobuf:"bytes,3,opt,name=item" json:"item,omitempty"`
}

func (m *NotifyChannelRequest) Reset()                    { *m = NotifyChannelRequest{} }
func (m *NotifyChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyChannelRequest) ProtoMessage()               {}
func (*NotifyChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NotifyChannelRequest) GetItem() *NotifyChannelRequest_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type NotifyChannelRequest_Item struct {
	Title  string                             `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Url    string                             `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Images []*NotifyChannelRequest_Item_Image `protobuf:"bytes,3,rep,name=images" json:"images,omitempty"`
	Videos []*NotifyChannelRequest_Item_Video `protobuf:"bytes,4,rep,name=videos" json:"videos,omitempty"`
}

func (m *NotifyChannelRequest_Item) Reset()                    { *m = NotifyChannelRequest_Item{} }
func (m *NotifyChannelRequest_Item) String() string            { return proto.CompactTextString(m) }
func (*NotifyChannelRequest_Item) ProtoMessage()               {}
func (*NotifyChannelRequest_Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *NotifyChannelRequest_Item) GetImages() []*NotifyChannelRequest_Item_Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *NotifyChannelRequest_Item) GetVideos() []*NotifyChannelRequest_Item_Video {
	if m != nil {
		return m.Videos
	}
	return nil
}

type NotifyChannelRequest_Item_Image struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *NotifyChannelRequest_Item_Image) Reset()         { *m = NotifyChannelRequest_Item_Image{} }
func (m *NotifyChannelRequest_Item_Image) String() string { return proto.CompactTextString(m) }
func (*NotifyChannelRequest_Item_Image) ProtoMessage()    {}
func (*NotifyChannelRequest_Item_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

type NotifyChannelRequest_Item_Video struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *NotifyChannelRequest_Item_Video) Reset()         { *m = NotifyChannelRequest_Item_Video{} }
func (m *NotifyChannelRequest_Item_Video) String() string { return proto.CompactTextString(m) }
func (*NotifyChannelRequest_Item_Video) ProtoMessage()    {}
func (*NotifyChannelRequest_Item_Video) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 1}
}

type NotifyChannelResponse struct {
}

func (m *NotifyChannelResponse) Reset()                    { *m = NotifyChannelResponse{} }
func (m *NotifyChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyChannelResponse) ProtoMessage()               {}
func (*NotifyChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NotifyAppendUserRequest struct {
	To string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
}

func (m *NotifyAppendUserRequest) Reset()                    { *m = NotifyAppendUserRequest{} }
func (m *NotifyAppendUserRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyAppendUserRequest) ProtoMessage()               {}
func (*NotifyAppendUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NotifyAppendUserResponse struct {
}

func (m *NotifyAppendUserResponse) Reset()                    { *m = NotifyAppendUserResponse{} }
func (m *NotifyAppendUserResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyAppendUserResponse) ProtoMessage()               {}
func (*NotifyAppendUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type NotifyDeleteUserRequest struct {
	To string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
}

func (m *NotifyDeleteUserRequest) Reset()                    { *m = NotifyDeleteUserRequest{} }
func (m *NotifyDeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyDeleteUserRequest) ProtoMessage()               {}
func (*NotifyDeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type NotifyDeleteUserResponse struct {
}

func (m *NotifyDeleteUserResponse) Reset()                    { *m = NotifyDeleteUserResponse{} }
func (m *NotifyDeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyDeleteUserResponse) ProtoMessage()               {}
func (*NotifyDeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type NotifyUstreamRequest struct {
	To []string `protobuf:"bytes,1,rep,name=to" json:"to,omitempty"`
}

func (m *NotifyUstreamRequest) Reset()                    { *m = NotifyUstreamRequest{} }
func (m *NotifyUstreamRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyUstreamRequest) ProtoMessage()               {}
func (*NotifyUstreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type NotifyUstreamResponse struct {
}

func (m *NotifyUstreamResponse) Reset()                    { *m = NotifyUstreamResponse{} }
func (m *NotifyUstreamResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyUstreamResponse) ProtoMessage()               {}
func (*NotifyUstreamResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*NotifyChannelRequest)(nil), "linebot.NotifyChannelRequest")
	proto.RegisterType((*NotifyChannelRequest_Item)(nil), "linebot.NotifyChannelRequest.Item")
	proto.RegisterType((*NotifyChannelRequest_Item_Image)(nil), "linebot.NotifyChannelRequest.Item.Image")
	proto.RegisterType((*NotifyChannelRequest_Item_Video)(nil), "linebot.NotifyChannelRequest.Item.Video")
	proto.RegisterType((*NotifyChannelResponse)(nil), "linebot.NotifyChannelResponse")
	proto.RegisterType((*NotifyAppendUserRequest)(nil), "linebot.NotifyAppendUserRequest")
	proto.RegisterType((*NotifyAppendUserResponse)(nil), "linebot.NotifyAppendUserResponse")
	proto.RegisterType((*NotifyDeleteUserRequest)(nil), "linebot.NotifyDeleteUserRequest")
	proto.RegisterType((*NotifyDeleteUserResponse)(nil), "linebot.NotifyDeleteUserResponse")
	proto.RegisterType((*NotifyUstreamRequest)(nil), "linebot.NotifyUstreamRequest")
	proto.RegisterType((*NotifyUstreamResponse)(nil), "linebot.NotifyUstreamResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for LineBot service

type LineBotClient interface {
	NotifyChannel(ctx context.Context, in *NotifyChannelRequest, opts ...grpc.CallOption) (*NotifyChannelResponse, error)
	NotifyAppendUser(ctx context.Context, in *NotifyAppendUserRequest, opts ...grpc.CallOption) (*NotifyAppendUserResponse, error)
	NotifyDeleteUser(ctx context.Context, in *NotifyDeleteUserRequest, opts ...grpc.CallOption) (*NotifyDeleteUserResponse, error)
	NotifyUstream(ctx context.Context, in *NotifyUstreamRequest, opts ...grpc.CallOption) (*NotifyUstreamResponse, error)
}

type lineBotClient struct {
	cc *grpc.ClientConn
}

func NewLineBotClient(cc *grpc.ClientConn) LineBotClient {
	return &lineBotClient{cc}
}

func (c *lineBotClient) NotifyChannel(ctx context.Context, in *NotifyChannelRequest, opts ...grpc.CallOption) (*NotifyChannelResponse, error) {
	out := new(NotifyChannelResponse)
	err := grpc.Invoke(ctx, "/linebot.LineBot/NotifyChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lineBotClient) NotifyAppendUser(ctx context.Context, in *NotifyAppendUserRequest, opts ...grpc.CallOption) (*NotifyAppendUserResponse, error) {
	out := new(NotifyAppendUserResponse)
	err := grpc.Invoke(ctx, "/linebot.LineBot/NotifyAppendUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lineBotClient) NotifyDeleteUser(ctx context.Context, in *NotifyDeleteUserRequest, opts ...grpc.CallOption) (*NotifyDeleteUserResponse, error) {
	out := new(NotifyDeleteUserResponse)
	err := grpc.Invoke(ctx, "/linebot.LineBot/NotifyDeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lineBotClient) NotifyUstream(ctx context.Context, in *NotifyUstreamRequest, opts ...grpc.CallOption) (*NotifyUstreamResponse, error) {
	out := new(NotifyUstreamResponse)
	err := grpc.Invoke(ctx, "/linebot.LineBot/NotifyUstream", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LineBot service

type LineBotServer interface {
	NotifyChannel(context.Context, *NotifyChannelRequest) (*NotifyChannelResponse, error)
	NotifyAppendUser(context.Context, *NotifyAppendUserRequest) (*NotifyAppendUserResponse, error)
	NotifyDeleteUser(context.Context, *NotifyDeleteUserRequest) (*NotifyDeleteUserResponse, error)
	NotifyUstream(context.Context, *NotifyUstreamRequest) (*NotifyUstreamResponse, error)
}

func RegisterLineBotServer(s *grpc.Server, srv LineBotServer) {
	s.RegisterService(&_LineBot_serviceDesc, srv)
}

func _LineBot_NotifyChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineBotServer).NotifyChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linebot.LineBot/NotifyChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineBotServer).NotifyChannel(ctx, req.(*NotifyChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LineBot_NotifyAppendUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyAppendUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineBotServer).NotifyAppendUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linebot.LineBot/NotifyAppendUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineBotServer).NotifyAppendUser(ctx, req.(*NotifyAppendUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LineBot_NotifyDeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineBotServer).NotifyDeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linebot.LineBot/NotifyDeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineBotServer).NotifyDeleteUser(ctx, req.(*NotifyDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LineBot_NotifyUstream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyUstreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineBotServer).NotifyUstream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/linebot.LineBot/NotifyUstream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineBotServer).NotifyUstream(ctx, req.(*NotifyUstreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LineBot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "linebot.LineBot",
	HandlerType: (*LineBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyChannel",
			Handler:    _LineBot_NotifyChannel_Handler,
		},
		{
			MethodName: "NotifyAppendUser",
			Handler:    _LineBot_NotifyAppendUser_Handler,
		},
		{
			MethodName: "NotifyDeleteUser",
			Handler:    _LineBot_NotifyDeleteUser_Handler,
		},
		{
			MethodName: "NotifyUstream",
			Handler:    _LineBot_NotifyUstream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("linebot/protos/linebot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x9b, 0xa4, 0x2f, 0x3c, 0xf3, 0xa0, 0x94, 0xa5, 0xd2, 0x18, 0x54, 0x6a, 0x0e, 0x52,
	0x2f, 0x29, 0x54, 0xf0, 0xec, 0xdb, 0xa5, 0x20, 0x22, 0x81, 0x0a, 0x1e, 0x5b, 0x3a, 0x6a, 0x20,
	0xcd, 0xc6, 0xec, 0x56, 0xf0, 0xd3, 0x7a, 0xf0, 0xe2, 0xc7, 0x70, 0x37, 0xd9, 0x36, 0xed, 0x6e,
	0x5b, 0x7b, 0xcb, 0x64, 0xfe, 0xf3, 0x9b, 0xcd, 0x8f, 0x0d, 0x1c, 0xc5, 0x51, 0x82, 0x63, 0xca,
	0x7b, 0x69, 0x46, 0x39, 0x65, 0x3d, 0x55, 0x06, 0x79, 0x49, 0x1a, 0xaa, 0xf4, 0xbf, 0x6c, 0x68,
	0x3d, 0x50, 0x1e, 0xbd, 0x7c, 0xde, 0xbe, 0x8d, 0x92, 0x04, 0xe3, 0x10, 0xdf, 0x67, 0xc8, 0x38,
	0xd9, 0x07, 0x9b, 0x53, 0xd7, 0xea, 0x38, 0xdd, 0x7f, 0xa1, 0x78, 0x22, 0x2d, 0xa8, 0xf1, 0x88,
	0xc7, 0xe8, 0xda, 0x1d, 0x4b, 0xbc, 0x2a, 0x0a, 0x72, 0x09, 0xd5, 0x88, 0xe3, 0xd4, 0x75, 0xc4,
	0xcb, 0xff, 0x7d, 0x3f, 0x98, 0x6f, 0x59, 0x87, 0x0c, 0x06, 0x22, 0x19, 0xe6, 0x79, 0xef, 0xc7,
	0x82, 0xaa, 0x2c, 0x4b, 0xac, 0xb5, 0x8c, 0x6d, 0x82, 0x33, 0xcb, 0x62, 0xb5, 0x4a, 0x3e, 0x92,
	0x2b, 0xa8, 0x47, 0xd3, 0xd1, 0x2b, 0x32, 0xb1, 0xca, 0x11, 0xab, 0xba, 0x7f, 0xaf, 0x0a, 0x06,
	0x72, 0x20, 0x54, 0x73, 0x92, 0xf0, 0x11, 0x4d, 0x90, 0x32, 0xb7, 0xba, 0x33, 0xe1, 0x49, 0x0e,
	0x84, 0x6a, 0xce, 0x3b, 0x84, 0x5a, 0x8e, 0x9c, 0x1f, 0xcf, 0x5a, 0x1c, 0x4f, 0xb6, 0xf2, 0xac,
	0xd9, 0xf2, 0xdb, 0x70, 0xa0, 0x2d, 0x60, 0x29, 0x4d, 0x18, 0xfa, 0xe7, 0xd0, 0x2e, 0x1a, 0xd7,
	0x69, 0x8a, 0xc9, 0x64, 0xc8, 0x30, 0xd3, 0xe5, 0x5b, 0x85, 0x7c, 0xdf, 0x03, 0xd7, 0x8c, 0xea,
	0x98, 0x3b, 0x8c, 0x91, 0xe3, 0x4e, 0x98, 0xe5, 0xa8, 0xc2, 0x9c, 0xcd, 0xef, 0xc1, 0x90, 0xf1,
	0x0c, 0x47, 0xd3, 0x0d, 0xf7, 0xa0, 0xfc, 0x9c, 0x45, 0xae, 0x00, 0xf4, 0xbf, 0x6d, 0x68, 0xdc,
	0x0b, 0xa3, 0x37, 0x94, 0x93, 0x47, 0xd8, 0x5b, 0xf9, 0x66, 0x72, 0xbc, 0x55, 0xb6, 0x77, 0xb2,
	0xa9, 0xad, 0x0e, 0x57, 0x21, 0xcf, 0xd0, 0xd4, 0x0d, 0x90, 0x8e, 0x36, 0x65, 0x78, 0xf4, 0x4e,
	0xb7, 0x24, 0x4c, 0x74, 0x69, 0xc5, 0x40, 0x1b, 0x6e, 0x0d, 0xf4, 0x1a, 0xa5, 0x95, 0xd2, 0x83,
	0x92, 0x65, 0x78, 0x58, 0x95, 0x6d, 0x78, 0xd0, 0x1c, 0xfb, 0x95, 0x71, 0x3d, 0xff, 0x7f, 0x2f,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xe3, 0xed, 0x4f, 0xdf, 0x03, 0x00, 0x00,
}
